app:
    name: Order Service
    version: 1.0.0
    description: Service for managing orders and billing
NODE_ENV: development
client:
    urls: http://localhost:5173,http://localhost:4173,http://localhost:3000
    application:
        url: http://localhost:3000
server:
    port: 8083
    host: localhost

auth:
    jwksUri: http://localhost:8081/.well-known/jwks.json